apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web-environment
spec:
  selector:
    matchLabels:
      run: hello-web-environment
  replicas: 2
  template:
    metadata:
      labels:
        run: hello-web-environment
    spec:
      containers:
      - name: hello-web-environment
        image: jollygnome/hellonode:buildNumber
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-web-environment
  labels:
    run: hello-web-environment
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
  selector:
    run: hello-web-environment
