apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: tst.joris.gluo.io
    http:
      paths:
      - backend:
          serviceName: tst/hello-web-tst
          servicePort: 80
  - host: uat.joris.gluo.io
    http:
      paths:
      - backend:
          serviceName: uat/hello-web-uat
          servicePort: 80
  - host: prd.joris.gluo.io
    http:
      paths:
      - backend:
          serviceName: prd/hello-web-prd
          servicePort: 80
