---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello-web
  name: hello-web
spec:
  replicas: 2
    spec:
      containers:
      - image: jollygnome/hellonode
        name: hello-web
        ports:
        - containerPort: 80
          protocol: TCP
