apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
spec:
  selector:
    matchLabels:
      run: hello-web
  replicas: 2
  template:
    metadata:
      labels:
        run: hello-web
    spec:
      containers:
      - name: hello-web
        image: jollygnome/hellonode
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-web
  labels:
    run: hello-web
spec:
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    run: hello-web
