apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: tst.joris.gluo.io
    http:
      paths:
      - backend:
          serviceName: hello-web-tst
          servicePort: 80
          nameSpace: tst
  - host: uat.joris.gluo.io
    http:
      paths:
      - backend:
          serviceName: hello-web-uat
          servicePort: 80
          nameSpace: uat
  - host: prd.joris.gluo.io
    http:
      paths:
      - backend:
          serviceName: hello-web-prd
          servicePort: 80
          nameSpace: prd
