apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: environment
spec:
  rules:
  - host: web.environment.k8s.joris.gluo.io
    http:
      paths:
      - backend:
          serviceName: hello-web-environment
          servicePort: 80
