apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: prd
spec:
  rules:
  - host: prd.joris.gluo.io
    http:
      paths:
      - backend:
          serviceName: hello-web-prd
          servicePort: 80
