---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello-web
  name: hello-web
spec:
  replicas: 2
    spec:
      containers:
      - image: jollygnome/hellonode
        name: hello-web
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello-web
  name: hello-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
