apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-web
spec:
  replicas: 2
  selector:
    app: hello-web
  template:
    metadata:
      name: hello-web
      labels:
        app: hello-web
    spec:
      containers:
      - name: hello-web
        image: jollygnome/hellonode
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello-web
  name: hello-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
