apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-web
spec:
  replicas: 3
  selector:
    app: hello-web
  template:
    metadata:
      name: hello-web
      labels:
        app: hello-web
    spec:
      containers:
        - name: hello-web
          image: jollygnome/hellonode
          ports:
          - contianerPort: 80 
